### ISSUE TITLE
Cannot parse output generated by newer versions of Futhark

### ISSUE THREAD

**Issue by athas** [pepijndevos/futhark-pycffi#6]
More recent versions of `futhark-opencl` generates accessor functions that expose OpenCL types directly, e.g:

```
*futhark_context_new_with_command_queue(struct futhark_context_config *cfg,
                                        cl_command_queue queue);
```

`build_futhark_ffi` fails to parse this:

```
Traceback (most recent call last):
  File "/home/mzd885/.local/bin/build_futhark_ffi", line 11, in <module>
    load_entry_point('futhark-ffi==0.6.1b2', 'console_scripts', 'build_futhark_ffi')()
  File "/home/mzd885/.local/lib/python2.7/site-packages/futhark_ffi/build.py", line 22, in main
    ffi = build(name)
  File "/home/mzd885/.local/lib/python2.7/site-packages/futhark_ffi/build.py", line 16, in build
    ffibuilder.cdef(cdef)
  File "/home/mzd885/.local/lib/python2.7/site-packages/cffi/api.py", line 106, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/home/mzd885/.local/lib/python2.7/site-packages/cffi/api.py", line 120, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/home/mzd885/.local/lib/python2.7/site-packages/cffi/cparser.py", line 308, in parse
    self._internal_parse(csource)
  File "/home/mzd885/.local/lib/python2.7/site-packages/cffi/cparser.py", line 313, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/home/mzd885/.local/lib/python2.7/site-packages/cffi/cparser.py", line 271, in _parse
    self.convert_pycparser_error(e, csource)
  File "/home/mzd885/.local/lib/python2.7/site-packages/cffi/cparser.py", line 300, in convert_pycparser_error
    raise CDefError(msg)
cffi.error.CDefError: cannot parse "cl_command_queue queue);"
```

Perfectly understandable, given that it does not know that this is a C type, but there must be some way to tell cffi what's going on...

**Comment by athas** [comment]
It might make the most sense to just ignore these functions.  I'm not sure how accessible they'd be from Python anyway.

**Comment by athas** [comment]
Alternatively, maybe it would be better if the functions took *pointers* to `cl_command_queue`...
